# Generated by Django 4.0.3 on 2022-04-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('unit_of_meas', models.CharField(blank=True, max_length=5)),
                ('price', models.FloatField(default=0.0)),
                ('point_man', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('date_start_use', models.DateField()),
                ('date_end_use', models.DateField()),
                ('last_update', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Update_hitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('item_id', models.PositiveBigIntegerField()),
                ('tbl_name', models.CharField(max_length=255)),
                ('prev_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Update_hitory',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Include_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('unit_of_meas', models.CharField(blank=True, max_length=5)),
                ('price', models.FloatField(default=0.0)),
                ('point_man', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('date_start_use', models.DateField()),
                ('date_end_use', models.DateField()),
                ('last_update', models.DateField(auto_now=True)),
                ('parrent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.items')),
            ],
            options={
                'db_table': 'Include_items',
            },
        ),
    ]
