# Generated by Django 4.0.3 on 2022-04-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_images_include_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='include_item_images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item_images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
