# Generated by Django 4.0.3 on 2022-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_include_item_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='include_item_images',
            name='image',
            field=models.ImageField(upload_to='images/subitem/'),
        ),
        migrations.AlterField(
            model_name='item_images',
            name='image',
            field=models.ImageField(upload_to='images/item/'),
        ),
    ]
